# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Books',
        ),
    ]
